### ISSUE TITLE
Doubt in footprint

### ISSUE THREAD

**Issue by Dhagash4** [larics/p3dx_config#6]
What is meant by footprint in common_params and how can I measure it?

**Comment by dmiklic** [comment]
It is a parameter used by the planners of the [ROS navigation stack](http://wiki.ros.org/navigation). It describes the physical dimensions of the robot, projected onto the ground plane. Here is a [tutorial](http://wiki.ros.org/navigation/Tutorials/RobotSetup) describing all navigation stack parameters.
